name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.1.5
environment:
  sdk: '>=2.0.0-dev.50.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+12
  angular_components: ^0.9.0-alpha+12
  angular_forms: ^2.0.0-alpha+4
  angular_router: ^2.0.0-alpha+11
  fo_model:
    git: https://github.com/afpatmin/fo_model.git
  grid:
    git: https://github.com/afpatmin/grid.git
  vi_auth_client: ^0.1.1
  sass_builder: ^2.0.0
